# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'TheMovieManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheMovieManager
  pod 'Alamofire', '~> 5.4'


end
